[package]
name = "litegallery"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
colored = "*"
spinners = "*"
rustyline = "11.0.0"

[dependencies.spinner]
version = "0.3"
