[package]
name = "litegallery"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
colored = "*"
spinners = "*"

[dependencies.spinner]
version = "0.3"
